image: Visual Studio 2017
init:
  - git config --global url."https://github.com/".insteadOf "git@github.com:"
configuration: Debug
install:
  - ps: Start-FileDownload 'https://dl.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.45.msi'
  - msiexec /i gtk-sharp-2.12.45.msi /quiet /qn /norestart
before_build:
  - dotnet restore
build:
  parallel: true
  project: Launchpad.sln
test:
  assemblies:
    only:
      - Launchpad.Tests.dll